pipeline:
  worker_count: 1
  buffer_size: 1000

log:
  level: "INFO"
  dir: "./logs"
  filename: "TunnelInsight.log"
  max_age: 24
  rotate_time: 1
  time_format: "2006-01-02 15:04:05"

output:
  type: "file"
  filename: "output.json"

source:
  type: "live"  # "file" 或 "live"
  filename: "ospf_hello_one.pcap"  # 当 type 为 "file" 时使用
  interface:  # 当 type 为 "live" 时使用
    name: "ens34"
    snaplen: 65535
    promiscuous: true
    timeout: 30s
    bpf_filter: ""

# API 服务配置
api:
  port: "8090"
  host: "10.107.12.243"  # 空字符串表示绑定所有IP

# 规则引擎配置
rule_engine:
  rule_directory: "rules/"

# 超时配置
timeouts:
  processor_ready_seconds: 10
  sink_ready_seconds: 5
  shutdown_seconds: 5
  processor_stop_seconds: 5

# 文件权限配置
permissions:
  directory_mode: 0755
  file_mode: 0644